name: Node.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 */6 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Run linters
      uses: wearerequired/lint-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Enable linters
        eslint: true
        prettier: true
    - run: |
        touch .env
        echo DISCORD=${{ secrets.DISCORD }} >> .env
        echo VOICETEXT=${{ secrets.VOICETEXT }} >> .env
        npm ci
        npm run build
        npm start